version: '3.8'
services:
  postgres_db:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - data_eng_network

  minio_storage:
    image: minio/minio:latest
    container_name: minio_storage
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000" # API Port
      - "9001:9001" # Console Port
    volumes:
      - minio_data:/data
    networks:
      - data_eng_network

  airflow-webserver:
    image: apache/airflow:2.8.1
    container_name: airflow_webserver
    command: webserver
    depends_on:
      - postgres_db
    ports:
      - "8080:8080"
    volumes:
      -./dags:/opt/airflow/dags
      -./logs:/opt/airflow/logs
      -./plugins:/opt/airflow/plugins
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres_db:5432/airflow
      - AIRFLOW__WEBSERVER__SECRET_KEY=your_secret_key_here
    networks:
      - data_eng_network

  spark-master:
    image: bitnami/spark:3.5
    container_name: spark_master
    environment:
      - SPARK_MODE=master
    ports:
      - "8081:8080" # Spark Master Web UI
      - "7077:7077"
    networks:
      - data_eng_network

  spark-worker:
    image: bitnami/spark:3.5
    container_name: spark_worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark_master:7077
    networks:
      - data_eng_network

networks:
  data_eng_network:
    driver: bridge

volumes:
  postgres_data:
  minio_data: